# Generated by Django 4.1.4 on 2023-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_about_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skills',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
